// generated by react
import Users from "./users/Users";
import './App.css';

function App() {
  return (
    <div>
      <Users title="User List" />
    </div>
  );
}

export default App;

// code from tutorial
// import React, { Component } from "react";
// import Users from './users/Users';
// import './App.css';

// class App extends Component {
//   render() {
//     return (
//       <div>
//         <Users/>
//       </div>
//     );
//   }
// }

// export default App;
